name: terraform

on:
  push:
  pull_request:

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: terraform setup
        uses: hashicorp/setup-terraform@v3

      - name: run make
        run: |
          make all
